title: GoGoSing
author: JinBum Jeong
email: gogosing@naver.com
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "/"

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: GoGoSing
  tagline: Developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false
  disqus_shortname: 'gogosing-github-io'

  # generate social links in footer
  social_links:
    github:  gogosing
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed